flowchart TD
    B0["0 01b4a954"]
    B1["1 01b4a9e0"]
    B2["2 01b4a9f4"]
    B3["3 01b4abe8"]
    B4["4 01b4abec"]
    B5["5 01b4ac00"]
    B6["6 01b4ac14"]
    B7["7 01b4ac20"]
    B8["8 01b4ac34"]
    B9["9 01b4ac40"]
    B10["10 01b4ac54"]
    B0 --> B1
    B1 --> B1
    B1 --> B2
    B2 --> B3
    B3 --> B4
    B4 --> B6
    B4 --> B5
    B5 --> B8
    B6 --> B8
    B6 --> B7
    B7 --> B8
    B8 --> B10
    B8 --> B9
    B9 --> B10
