flowchart TD
    B0["0 01cbfb88"]
    B1["1 01cbfb9c"]
    B2["2 01cbfbc0"]
    B3["3 01cbfbd4"]
    B4["4 01cbfbd8"]
    B5["5 01cbfbe8"]
    B6["6 01cbfbf0"]
    B7["7 01cbfbf4"]
    B8["8 01cbfc08"]
    B9["9 01cbfc14"]
    B10["10 01cbfc18"]
    B11["11 01cbfc38"]
    B12["12 01cbfc3c"]
    B13["13 01cbfc54"]
    B14["14 01cbfc5c"]
    B15["15 01cbfc68"]
    B16["16 01cbfc74"]
    B17["17 01cbfc9c"]
    B0 --> B1
    B1 --> B3
    B1 --> B2
    B2 --> B4
    B3 --> B4
    B4 --> B6
    B4 --> B5
    B6 --> B10
    B6 --> B7
    B7 --> B9
    B7 --> B8
    B9 --> B10
    B10 --> B15
    B10 --> B11
    B11 --> B12
    B12 --> B12
    B12 --> B13
    B13 --> B15
    B13 --> B14
    B14 --> B17
    B14 --> B15
    B15 --> B16
    B17 --> B16
