flowchart TD
    B0["0 001e9c80"]
    B1["1 001e9cb8"]
    B2["2 001e9cd0"]
    B3["3 001e9ce8"]
    B4["4 001e9cf0"]
    B5["5 001e9cf8"]
    B6["6 001e9d00"]
    B7["7 001e9d08"]
    B8["8 001e9d20"]
    B9["9 001e9d24"]
    B0 --> B4
    B0 --> B1
    B1 --> B4
    B1 --> B2
    B2 --> B7
    B2 --> B3
    B3 --> B4
    B4 --> B8
    B4 --> B5
    B5 --> B8
    B5 --> B6
    B6 --> B9
    B8 --> B9
