flowchart TD
    B0["0 001faeb0"]
    B1["1 001faef4"]
    B2["2 001faf0c"]
    B3["3 001faf24"]
    B4["4 001faf2c"]
    B5["5 001faf34"]
    B6["6 001faf3c"]
    B7["7 001faf44"]
    B8["8 001faf5c"]
    B9["9 001faf60"]
    B10["10 001faf88"]
    B11["11 001faf98"]
    B12["12 001faf9c"]
    B0 --> B4
    B0 --> B1
    B1 --> B4
    B1 --> B2
    B2 --> B7
    B2 --> B3
    B3 --> B4
    B4 --> B8
    B4 --> B5
    B5 --> B8
    B5 --> B6
    B6 --> B9
    B8 --> B9
    B9 --> B11
    B9 --> B10
    B10 --> B12
    B11 --> B12
