flowchart TD
    B0["0 001df850"]
    B1["1 001df874"]
    B2["2 001df8b4"]
    B3["3 001df8cc"]
    B4["4 001df8e4"]
    B5["5 001df8ec"]
    B6["6 001df910"]
    B7["7 001df918"]
    B8["8 001df93c"]
    B9["9 001df94c"]
    B0 --> B8
    B0 --> B1
    B1 --> B5
    B1 --> B2
    B2 --> B5
    B2 --> B3
    B3 --> B9
    B3 --> B4
    B4 --> B5
    B5 --> B7
    B5 --> B6
    B6 --> B7
