flowchart TD
    B0["0 0029cf10"]
    B1["1 0029cf60"]
    B2["2 0029cf78"]
    B3["3 0029cf90"]
    B4["4 0029cf98"]
    B5["5 0029cfa0"]
    B6["6 0029cfa8"]
    B7["7 0029cfb0"]
    B8["8 0029cfc8"]
    B9["9 0029cfcc"]
    B0 --> B4
    B0 --> B1
    B1 --> B4
    B1 --> B2
    B2 --> B7
    B2 --> B3
    B3 --> B4
    B4 --> B8
    B4 --> B5
    B5 --> B8
    B5 --> B6
    B6 --> B9
    B8 --> B9
