flowchart TD
    B0["0 01a2af50"]
    B1["1 01a2af6c"]
    B2["2 01a2afe4"]
    B3["3 01a2afe8"]
    B4["4 01a2aff8"]
    B5["5 01a2b018"]
    B6["6 01a2b02c"]
    B7["7 01a2b03c"]
    B8["8 01a2b044"]
    B9["9 01a2b050"]
    B0 --> B4
    B0 --> B1
    B1 --> B3
    B1 --> B2
    B3 --> B9
    B4 --> B6
    B4 --> B5
    B5 --> B6
    B6 --> B8
    B6 --> B7
    B8 --> B9
