import csv
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FUNCS_DIR = os.path.join(ROOT, "funcs")
SNIFFER_ROOT = os.path.normpath(os.path.join(ROOT, "..", "ssbu-call-sniffer"))
OUT_DIR = os.path.join(SNIFFER_ROOT, "src", "hooks")

IDENT_RE = re.compile(r"[^A-Za-z0-9_]+")

PRELUDE = """// Auto-generated by ssbu-atamol-research/scripts/generate_hooks.py from ssbu-atamol-research/funcs/funcs_{cat}.csv
// Do not edit manually. Re-run the script to refresh

use crate::logger;

"""


def safe_ident(name, fallback):
    n = IDENT_RE.sub("_", name).strip("_")
    if not n or n[0].isdigit():
        n = "_" + n
    if not n:
        n = fallback
    return n[:80].lower()


def parse_offset(s):
    s = (s or "").strip().lower()
    if not s:
        return None
    if s.startswith("0x"):
        s = s[2:]
    try:
        return int(s, 16)
    except ValueError:
        return None


def to_int(s, default=0):
    try:
        return int((s or "").strip())
    except ValueError:
        return default


def pick_name(row):
    # priority: ssbu-decomp confirmed > heuristic suggestion > demangled > FUN name
    en = (row.get("External Names") or "").strip()
    if en and "@ssbu-decomp" in en:
        return en.split("@", 1)[0]
    sn = (row.get("Suggested Name") or "").strip()
    if sn:
        return sn
    dm = (row.get("Function Demangled") or "").strip()
    if dm:
        return dm
    return ""


def load_funcs_all_index():
    # build addr -> row map from funcs/funcs_all.csv (used to enrich hash40 candidates)
    path = os.path.join(FUNCS_DIR, "funcs_all.csv")
    by_off = {}
    if not os.path.isfile(path):
        return by_off
    with open(path, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            off = parse_offset(row.get("Function Offset"))
            if off is not None:
                by_off[off] = row
    return by_off


def load_hash40_candidates():
    # group hash40_loads.csv by Function Address -> count of distinct hash40 loaded
    path = os.path.join(ROOT, "tables", "hash40_loads.csv")
    if not os.path.isfile(path):
        return []
    counts = {}
    info = {}
    with open(path, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            addr = parse_offset(row.get("Function Address"))
            if addr is None:
                continue
            counts[addr] = counts.get(addr, 0) + 1
            if addr not in info:
                info[addr] = {
                    "Function Address": "{:08x}".format(addr),
                    "Function Offset": "0x{:x}".format(addr),
                    "Function Name": (row.get("Function Name") or "").strip(),
                    "Function Symbol": (row.get("Function Symbol") or "").strip(),
                    "Function Demangled": (row.get("Function Demangled") or "").strip(),
                }
    rows = []
    for addr, c in counts.items():
        r = dict(info[addr])
        r["Hash40 Loads"] = str(c)
        rows.append(r)
    rows.sort(key=lambda r: -to_int(r.get("Hash40 Loads")))
    return rows


def filter_candidates(rows, min_refs, max_size):
    out = []
    for row in rows:
        sym = (row.get("Function Symbol") or "").strip()
        if sym.startswith("_Z"):
            out.append(row)
            continue
        refs = to_int(row.get("Function Incoming Refs"))
        size = to_int(row.get("Function Size"))
        if refs < min_refs:
            continue
        if max_size > 0 and size > 0 and size > max_size:
            continue
        fn_name = (row.get("Function Name") or "").strip()
        callers = (row.get("Callers") or "")
        if fn_name and fn_name in callers:
            continue
        out.append(row)
    return out


def gen_one(category, top_n, min_refs, max_size, replace, sample_after, sample_every, global_seen, funcs_index):
    if category == "hash40":
        # virtual category: candidate set is functions that load hash40 constants
        # enrich with full func metadata when available so safety filters work
        raw = load_hash40_candidates()
        if not raw:
            print("missing tables/hash40_loads.csv")
            return False
        candidates = []
        for r in raw:
            off = parse_offset(r.get("Function Offset"))
            if off is None or off in global_seen:
                continue
            global_seen.add(off)
            enrich = funcs_index.get(off)
            if enrich:
                merged = dict(enrich)
                merged["Hash40 Loads"] = r.get("Hash40 Loads", "")
                candidates.append(merged)
            else:
                candidates.append(r)
        candidates = filter_candidates(candidates, min_refs, max_size)
        candidates.sort(key=lambda r: -to_int(r.get("Hash40 Loads")))
        rows = candidates[:top_n]
    else:
        in_path = os.path.join(FUNCS_DIR, "funcs_{0}.csv".format(category))
        if not os.path.isfile(in_path):
            print("missing {0}".format(in_path))
            return False
        candidates = []
        with open(in_path, "r", encoding="utf-8") as f:
            r = csv.DictReader(f)
            for row in r:
                sym = (row.get("Function Symbol") or "").strip()
                off = parse_offset(row.get("Function Offset"))
                if not sym.startswith("_Z") and off is None:
                    continue
                if off is not None:
                    if off in global_seen:
                        continue
                    global_seen.add(off)
                candidates.append(row)
        candidates = filter_candidates(candidates, min_refs, max_size)
        candidates.sort(key=lambda r: -to_int(r.get("Function Incoming Refs")))
        rows = candidates[:top_n]

    out_path = os.path.join(OUT_DIR, "{0}.rs".format(category))
    used = set()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(PRELUDE.format(cat=category))

        # extern block only for symbol-based hooks
        sym_rows = [r for r in rows if (r.get("Function Symbol") or "").startswith("_Z")]
        if sym_rows:
            f.write('extern "C" {\n')
            for row in sym_rows:
                base = row.get("Function Name") or "fn"
                base = base.split("::")[-1]
                ident = safe_ident(base, "fn")
                n = 2
                while ident in used:
                    ident = "{0}_{1}".format(ident, n)
                    n += 1
                used.add(ident)
                row["_ident"] = ident
                f.write('    #[link_name = "{0}"]\n'.format(row["Function Symbol"]))
                f.write("    fn target_{0}(x0:u64,x1:u64,x2:u64,x3:u64,x4:u64,x5:u64,x6:u64,x7:u64)->u64;\n".format(ident))
            f.write("}\n\n")

        # assign idents to offset-only rows. prefer human name, fall back to off_xxx
        for row in rows:
            if "_ident" in row:
                continue
            off = parse_offset(row.get("Function Offset"))
            human = pick_name(row)
            row["_human"] = human
            base = human or row.get("Function Name") or ""
            base = base.split("::")[-1]
            if not base or base.startswith("FUN_"):
                base = "off_{0:x}".format(off)
            ident = safe_ident(base, "fn")
            # disambiguate name collisions by appending offset
            if ident in used:
                ident = "{0}_{1:x}".format(ident, off)
            n = 2
            while ident in used:
                ident = "{0}_{1}".format(ident, n)
                n += 1
            used.add(ident)
            row["_ident"] = ident

        # default: inline hook (4-byte atomic patch, race-safe, captures LR for dynamic xref)
        # --replace: prologue replace (20-byte overwrite, full enter+exit+ret, no LR, races with running threads)
        # symbol-based hooks always use replace since the linker resolves the entry
        for row in rows:
            ident = row["_ident"]
            sym = (row.get("Function Symbol") or "").strip()
            off = parse_offset(row.get("Function Offset"))
            row["_id"] = off if off is not None else 0
            if sym.startswith("_Z") or replace:
                if sym.startswith("_Z"):
                    f.write('#[skyline::hook(replace = target_{0})]\n'.format(ident))
                else:
                    f.write('#[skyline::hook(offset = 0x{0:x})]\n'.format(off))
                f.write("unsafe fn hook_{0}(x0:u64,x1:u64,x2:u64,x3:u64,x4:u64,x5:u64,x6:u64,x7:u64)->u64 {{\n".format(ident))
                f.write("    logger::log_enter(0x{0:x}, 0, [x0,x1,x2,x3,x4,x5,x6,x7]);\n".format(row["_id"]))
                f.write("    let r = call_original!(x0,x1,x2,x3,x4,x5,x6,x7);\n")
                f.write("    logger::log_exit(0x{0:x}, r);\n".format(row["_id"]))
                f.write("    r\n")
                f.write("}\n\n")
            else:
                f.write('#[skyline::hook(offset = 0x{0:x}, inline)]\n'.format(off))
                f.write("unsafe fn hook_{0}(ctx: &skyline::hooks::InlineCtx) {{\n".format(ident))
                # per-hook sampling. log first sample_after hits in full, then every sample_every-th
                # (set sample_every=1 for no sampling)
                if sample_every > 1:
                    f.write("    static N: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);\n")
                    f.write("    let n = N.fetch_add(1, std::sync::atomic::Ordering::Relaxed);\n")
                    f.write("    if n >= {0} && n % {1} != 0 {{ return; }}\n".format(sample_after, sample_every))
                f.write("    logger::log_enter(0x{0:x}, ctx.registers[30].x(), [\n".format(row["_id"]))
                for i in range(8):
                    f.write("        ctx.registers[{0}].x(),\n".format(i))
                f.write("    ]);\n")
                f.write("}\n\n")

        f.write("pub fn install() {\n")
        f.write("    skyline::install_hooks!(\n")
        for row in rows:
            f.write("        hook_{0},\n".format(row["_ident"]))
        f.write("    );\n")
        f.write("}\n")
    print("wrote {0} ({1} hooks)".format(out_path, len(rows)))

    catalog_path = os.path.join(SNIFFER_ROOT, "call_sniffer_funcs_{0}.csv".format(category))
    with open(catalog_path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Ident", "Function Address", "Function Offset", "Hint Name", "Function Name", "Function Symbol", "Function Demangled", "Function Signature"])
        for row in rows:
            w.writerow([row["_ident"], row.get("Function Address", ""), row.get("Function Offset", ""),
                        row.get("_human", ""),
                        row.get("Function Name", ""), row.get("Function Symbol", ""),
                        row.get("Function Demangled", ""), row.get("Function Signature", "")])
    print("wrote {0}".format(catalog_path))
    return True


def main():
    if len(sys.argv) < 2:
        print("usage: generate_hooks.py <category> [...] [--top=N] [--min-refs=N] [--max-size=N] [--replace] [--sample-after=N --sample-every=M]")
        sys.exit(1)
    top_n = 50
    min_refs = 0
    max_size = 2000
    replace = False
    sample_after = 32
    sample_every = 1   # 1 = no sampling
    cats = []
    for a in sys.argv[1:]:
        if a.startswith("--top="):
            top_n = int(a.split("=", 1)[1])
        elif a.startswith("--min-refs="):
            min_refs = int(a.split("=", 1)[1])
        elif a.startswith("--max-size="):
            max_size = int(a.split("=", 1)[1])
        elif a.startswith("--sample-after="):
            sample_after = int(a.split("=", 1)[1])
        elif a.startswith("--sample-every="):
            sample_every = int(a.split("=", 1)[1])
        elif a == "--replace":
            replace = True
        else:
            cats.append(a)
    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)
    ok = True
    global_seen = set()
    funcs_index = load_funcs_all_index()
    for cat in cats:
        if not gen_one(cat, top_n, min_refs, max_size, replace, sample_after, sample_every, global_seen, funcs_index):
            ok = False
    if not ok:
        sys.exit(1)
    print("\nremember to add 'mod {0};' lines and the install() calls in ../ssbu-call-sniffer/src/hooks/mod.rs".format(cats[0] if cats else "<category>"))


if __name__ == "__main__":
    main()
